import os
import gzip
import sys

configfile: "config/config.yaml"

container: "continuumio/miniconda3:4.8.2"


OUTDIR = config["outdir"]

TARGET_GENES = ['abcb1', 'cacna1s', 'cftr', 'cyp1a1', 'cyp1a2', 
                'cyp1b1', 'cyp2a6','cyp2a13', 'cyp2b6', 'cyp2c8', 
                'cyp2c9', 'cyp2c19','cyp2d6', 'cyp2e1', 'cyp2f1', 
                'cyp2j2', 'cyp2r1','cyp2s1', 'cyp2w1', 'cyp3a4', 
                'cyp3a5', 'cyp3a7','cyp3a43', 'cyp4a11', 'cyp4a22', 
                'cyp4b1', 'cyp4f2','cyp17a1', 'cyp19a1', 'cyp26a1', 
                'dpyd', 'g6pd','gstm1', 'gstp1', 'gstt1', 
                'ifnl3', 'nat1', 'nat2','nudt15', 'por', 
                'ptgis', 'ryr1', 'slc15a2','slc22a2', 'slco1b1', 'slco1b3', 
                'slco2b1', 'sult1a1','tbxas1', 'tpmt', 'ugt1a1', 
                'ugt1a4', 'ugt2b7','ugt2b15', 'ugt2b17', 'vkorc1', 
                'xpc']

CONTROL_GENE = 'vdr'

css_file    = "workflow/resources/report/css/styles.css"
js_file     = "workflow/resources/report/js/scripts.js"
css_heading = "workflow/resources/report/css/heading.css"
css_heading = "workflow/resources/report/css/body.css"





#if config["datatype"] == "ILLUMINA":
#
#    rule all:
#        input:        
#            expand(f"{OUTDIR}/{{sample}}/qc/fastqc/{{sample}}_fastqc.zip", sample=config["samples"]),
#            expand(f"{OUTDIR}/{{sample}}/qc/samtools/{{sample}}.{{mapper}}.{{provider}}.bam.stats.txt", sample=config["samples"], mapper="pbmm2", provider="pacbio"),
#            expand(f"{OUTDIR}/{{sample}}/qc/multiqc/multiqc.{{mapper}}.{{provider}}.{{caller}}.html", sample=config["samples"], mapper="pbmm2", provider="pacbio", caller="pepper")



# Target rules #

if config["datatype"] == "NANOPORE":
    
    provider = "nanopore"
    mapper = "minimap2"
    caller = "pepper"
    
    rule all:
        input:
            expand(f"{OUTDIR}/{{sample}}/qc/nanoplot/{{sample}}.bam.NanoPlot-report.html", sample=config["samples"])

if config["datatype"] == "PACBIO":
    
    provider = "pacbio"
    mapper = "pbmm2"
    caller = "pepper"

    rule all:
        input:
            expand(f"{OUTDIR}/{{sample}}/qc/mosdepth/{{sample}}.{config['build']}.mosdepth.inferred_sex.txt", sample=config["samples"]),
            expand(f"{OUTDIR}/{{sample}}/qc/mosdepth/{{sample}}.{config['build']}.mosdepth.M2_ratio.txt", sample=config["samples"]),
            expand(f"{OUTDIR}/{{sample}}/qc/mosdepth/{{sample}}.{config['build']}.gc_coverage.summary.txt", sample=config["samples"]),
            expand(f"{OUTDIR}/{{sample}}/stargazer/gdf/{{target_gene}}/{{sample}}.{{target_gene}}.gdf", sample=config["samples"], target_gene=TARGET_GENES)

if config["datatype"] == "ILLUMINA":
    
    provider = "illumina"
    mapper = "minimap2"
    caller = "deepvariant"
    
    rule all:
        input:
            expand(f"{OUTDIR}/{{sample}}/qc/nanoplot/{{sample}}.bam.NanoPlot-report.html", sample=config["samples"])



include: "rules/mapping.smk"
include: "rules/calling.smk"
include: "rules/qc.smk"
include: "rules/stargazer.smk"
#include: "rules/report.smk"
