def Azathioprine_recommendation(pt: str) -> str:
    recommendation = ""
    s1 = "nudt15"
    s2 = "tpmt"
    if s1 in pt and s2 in pt:
        if pt[s1] == "normal_metabolizer" and pt[s2] == "normal_metabolizer":
            recommendation = "Use standard dose."
        elif pt[s1] == "normal_metabolizer" and pt[s2] == "intermediate_metabolizer":
            recommendation = "Azathioprine can be affected by a patient’s TPMT and NUDT15 phenotype. This patient is predicted to be TPMT intermediate metabolizer and NUDT15 normal metabolizer. This patient is at risk for myelosuppression with normal doses of Azathioprine. Start with reduced starting doses (30\%\-80\% \of normal dose) if normal starting dose is 2-3 mg/kg/day, (e.g. 0.6 – 2.4 mg/kg/day), and adjust doses of Azathioprine based on degree of myelosuppression and disease-specific guidelines. Allow 2-4 weeks to reach steady-state after each dose adjustment. Please consult a clinical pharmacist for more information."
        elif pt[s1] == "normal_metabolizer" and pt[s2] == "poor_metabolizer":
            recommendation = "Azathioprine can be affected by a patient’s TPMT and NUDT15 phenotype. This patient is predicted to be a TPMT poor metabolizer and NUDT15 normal metabolizer. This patient is at high risk for life threatening myelosuppression with normal doses of Azathioprine and should receive greatly reduced doses. For non-malignant conditions, consider alternative non-thiopurine immunosuppressant therapy. For malignant conditions, start with drastically reduced normal daily doses (reduce daily dose by 10 fold and dose thrice weekly instead of daily) and adjust doses of Azathioprine based on degree of myelosuppression and disease-specific guidelines. Allow 4-6 weeks to reach steady-state after each dose adjustment. Please consult a clinical pharmacist for more information."
        elif pt[s1] == "intermediate_metabolizer" and pt[s2] == "normal_metabolizer":
            recommendation = "Azathioprine can be affected by a patient’s TPMT and NUDT15 phenotype. This patient is predicted to be a TPMT normal metabolizer and NUDT15 intermediate metabolizer. This patient is at risk for myelosuppression with normal doses of Azathioprine. Start with reduced starting doses (30\%\-80\% \of normal dose) if normal starting dose is 2-3 mg/kg/day, (e.g. 0.6 – 2.4 mg/kg/day), and adjust doses of Azathioprine based on degree of myelosuppression and disease-specific guidelines. Allow 2-4 weeks to reach steady-state after each dose adjustment. Please consult a clinical pharmacist for more information."
        elif pt[s1] == "decreased_function" and pt[s2] == "decreased_function":
            recommendation = "Azathioprine can be affected by a patient’s TPMT and NUDT15 phenotype. This patient is predicted to be TPMT intermediate metabolizer and NUDT15 intermediate metabolizer. This patient is at risk for myelosuppression with normal doses of Azathioprine. Start with reduced starting doses (30%-80% of normal dose) if normal starting dose is 2-3 mg/kg/day, (e.g. 0.6 – 2.4 mg/kg/day), and adjust doses of Azathioprine based on degree of myelosuppression and disease-specific guidelines. Allow 2-4 weeks to reach steady-state after each dose adjustment. Please consult a clinical pharmacist for more information."
        elif pt[s1] == "intermediate_metabolizer" and pt[s2] == "poor_metabolizer":
            recommendation = "Azathioprine can be affected by a patient’s TPMT and NUDT15 phenotype. This patient is predicted to be a TPMT poor metabolizer and NUDT15 intermediate metabolizer. This patient is at high risk for life threatening myelosuppression with normal doses of Azathioprine and should receive greatly reduced doses. For non-malignant conditions, consider alternative non-thiopurine immunosuppressant therapy. For malignant conditions, start with drastically reduced normal daily doses (reduce daily dose by 10 fold and dose thrice weekly instead of daily) and adjust doses of Azathioprine based on degree of myelosuppression and disease-specific guidelines. Allow 4-6 weeks to reach steady-state after each dose adjustment. Please consult a clinical pharmacist for more information."
        elif pt[s1] == "poor_metabolizer" and pt[s2] == "normal_metabolizer":
            recommendation = "Azathioprine can be affected by a patient’s TPMT and NUDT15 phenotype. This patient is predicted to be a TPMT normal metabolizer and NUDT15 poor metabolizer. This patient is at high risk for life threatening myelosuppression with normal doses of Azathioprine and should receive greatly reduced doses. For non-malignant conditions, consider alternative non-thiopurine immunosuppressant therapy. For malignant conditions, start with drastically reduced normal daily doses (reduce daily dose by 10 fold and dose thrice weekly instead of daily) and adjust doses of Azathioprine based on degree of myelosuppression and disease-specific guidelines. Allow 4-6 weeks to reach steady-state after each dose adjustment. Please consult a clinical pharmacist for more information."
        elif pt[s1] == "poor_metabolizer" and pt[s2] == "intermediate_metabolizer":
            recommendation = "Azathioprine can be affected by a patient’s TPMT and NUDT15 phenotype. This patient is predicted to be a TPMT poor metabolizer and NUDT15 poor metabolizer. This patient is at high risk for life threatening myelosuppression with normal doses of Azathioprine and should receive greatly reduced doses. For non-malignant conditions, consider alternative non-thiopurine immunosuppressant therapy. For malignant conditions, start with drastically reduced normal daily doses (reduce daily dose by 10 fold and dose thrice weekly instead of daily) and adjust doses of Azathioprine based on degree of myelosuppression and disease-specific guidelines. Allow 4-6 weeks to reach steady-state after each dose adjustment. Please consult a clinical pharmacist for more information."
        elif pt[s1] == "poor_metabolizer" and pt[s2] == "poor_metabolizer":
            recommendation = "Azathioprine can be affected by a patient’s TPMT and NUDT15 phenotype. This patient is predicted to be a TPMT poor metabolizer and NUDT15 poor metabolizer. This patient is at high risk for life threatening myelosuppression with normal doses of Azathioprine and should receive greatly reduced doses. For non-malignant conditions, consider alternative non-thiopurine immunosuppressant therapy. For malignant conditions, start with drastically reduced normal daily doses (reduce daily dose by 10 fold and dose thrice weekly instead of daily) and adjust doses of Azathioprine based on degree of myelosuppression and disease-specific guidelines. Allow 4-6 weeks to reach steady-state after each dose adjustment. Please consult a clinical pharmacist for more information."    
        else:
            recommendation = "No recommendation"
    elif s1 in pt and s2 not in pt:
        if pt[s1] == "normal_metabolizer":
            recommendation = "Azathioprine can be affected by a patient’s TPMT and NUDT15 phenotype. This patient is predicted to be a NUDT15 normal metabolizer; there is no reason to selectively adjust the dose of this medication based on the NUDT15 result. Because a TPMT genotype does not appear to have been ordered for this patient, it is not known if TPMT results would influence the recommended dose or drug. Please consult a clinical pharmacist for more information."
        elif pt[s1] == "intermediate_metabolizer":
            recommendation = "Azathioprine can be affected by a patient’s TPMT and NUDT15 phenotype. This patient is predicted to be a NUDT15 intermediate metabolizer and is at risk for myelosuppression with normal doses of Azathioprine. Start with reduced starting doses (30\%\-80\% \of normal dose) if normal starting dose is 2-3 mg/kg/day, (e.g. 0.6 – 2.4 mg/kg/day), and adjust doses of Azathioprine based on degree of myelosuppression and disease-specific guidelines. Allow 2-4 weeks to reach steady-state after each dose adjustment.  Because a TPMT genotype does not appear to have been ordered for this patient, it is not known if TPMT results would further influence the recommended dose or drug.  Please consult a clinical pharmacist for more information."
        elif pt[s1] == "poor_metabolizer":
            recommendation = "Azathioprine can be affected by a patient’s TPMT and NUDT15 phenotype. This patient is predicted to be a NUDT15 poor metabolizer and is at high risk for life threatening myelosuppression with normal doses of Azathioprine and should receive greatly reduced doses. For non-malignant conditions, consider alternative non-thiopurine immunosuppressant therapy. For malignant conditions, start with drastically reduced normal daily doses (reduce daily dose by 10 fold and dose thrice weekly instead of daily) and adjust doses of Azathioprine based on degree of myelosuppression and disease-specific guidelines. Allow 4-6 weeks to reach steady-state after each dose adjustment.  Because a TPMT genotype does not appear to have been ordered for this patient, it is not known if TPMT results would further influence the recommended dose or drug. Please consult a clinical pharmacist for more information."
        else:
            recommendation = "No recommendation"
    elif s1 not in pt and s2 in pt:
        if pt[s2] == "normal_metabolizer":
            recommendation = "Azathioprine can be affected by a patient’s TPMT and NUDT15 phenotype. This patient is predicted to be a TPMT normal metabolizer; there is no reason to selectively adjust the dose of this medication based on the TPMT result. Because a NUDT15 genotype does not appear to have been ordered for this patient, it is not known if NUDT15 results would further influence the recommended dose or drug. Please consult a clinical pharmacist for more information."
        elif pt[s2] == "intermediate_metabolizer":
            recommendation = "Azathioprine can be affected by a patient’s TPMT and NUDT15 phenotype. This patient is predicted to be TPMT intermediate metabolizer and is at risk for myelosuppression with normal doses of Azathioprine. Start with reduced starting doses (30\%\-80\% \of normal dose) if normal starting dose is 2-3 mg/kg/day, (e.g. 0.6 – 2.4 mg/kg/day), and adjust doses of Azathioprine based on degree of myelosuppression and disease-specific guidelines. Allow 2-4 weeks to reach steady-state after each dose adjustment. Because a NUDT15 genotype does not appear to have been ordered for this patient,  it is not known if NUDT15 results would further influence the recommended dose or drug. Please consult a clinical pharmacist for more information."
        elif pt[s2] == "poor_metabolizer":
            recommendation = "Azathioprine can be affected by a patient’s TPMT and NUDT15 phenotype. This patient is predicted to be a TPMT poor metabolizer and is at high risk for life threatening myelosuppression with normal doses of Azathioprine and should receive greatly reduced doses. For non-malignant conditions, consider alternative non-thiopurine immunosuppressant therapy. For malignant conditions, start with drastically reduced normal daily doses (reduce daily dose by 10 fold and dose thrice weekly instead of daily) and adjust doses of Azathioprine based on degree of myelosuppression and disease-specific guidelines. Allow 4-6 weeks to reach steady-state after each dose adjustment.  Because a NUDT15 genotype does not appear to have been ordered for this patient, it is not known if NUDT15 results would further influence the recommended dose or drug. Please consult a clinical pharmacist for more information."
        else:
            recommendation = "No recommendation"
    elif s1 not in pt and s2 not in pt: 
        recommendation = "No recommendation"
    return recommendation
