def Mercaptopurine_recommendation(pt: str) -> str:
    recommendation = ""
    s1 = "nudt15"
    s2 = "tpmt"
    if s1 in pt and s2 in pt:
        if pt[s1] == "normal_metabolizer" and pt[s2] == "normal_metabolizer":
            recommendation = "Use standard dose."
        elif pt[s1] == "normal_metabolizer" and pt[s2] == "intermediate_metabolizer":
            recommendation = "6-Mercaptopurine can be affected by a patient’s TPMT and NUDT15 phenotype. This patient is predicted to be TPMT intermediate metabolizer and NUDT15 normal metabolizer. This patient is at risk for myelosuppression with normal doses of 6-Mercaptopurine. Consider starting 6-Mercaptopurine at 30-80\% \of normal dose if normal starting dose is ≥75 mg/m2/day or ≥ 1.5 mg/kg/day  (e.g., start at 25-60 mg/m2/day or 0.45-1.2 mg/kg/day) and adjust doses of Mercaptopurine based on degree of myelosuppression and disease-specific guidelines. Allow 2-4 weeks to reach steady-state after each dose adjustment. If myelosuppression occurs, and depending on other therapy, emphasis should be on reducing Mercaptopurine over other agents. If normal starting dose is already <75mg/m2/day or < 1.5mg/kg/day, dose reduction may not be recommended. Please consult a clinical pharmacist for more information."
        elif pt[s1] == "normal_metabolizer" and pt[s2] == "poor_metabolizer":
            recommendation = "6-Mercaptopurine can be affected by a patient’s TPMT and NUDT15 phenotype. This patient is predicted to be possible TPMT intermediate metabolizer and NUDT15 normal metabolizer. This patient is at risk for myelosuppression with normal doses of 6-Mercaptopurine. Consider starting 6-Mercaptopurine at 30-80\% \of normal dose if normal starting dose is ≥75 mg/m2/day or ≥ 1.5 mg/kg/day  (e.g., start at 25-60 mg/m2/day or 0.45-1.2 mg/kg/day) and adjust doses of Mercaptopurine based on degree of myelosuppression and disease-specific guidelines. Allow 2-4 weeks to reach steady-state after each dose adjustment. If myelosuppression occurs, and depending on other therapy, emphasis should be on reducing Mercaptopurine over other agents. If normal starting dose is already <75mg/m2/day or < 1.5mg/kg/day, dose reduction may not be recommended. Please consult a clinical pharmacist for more information."
        elif pt[s1] == "intermediate_metabolizer" and pt[s2] == "normal_metabolizer":
            recommendation = "6-Mercaptopurine can be affected by a patient’s TPMT and NUDT15 phenotype. This patient is predicted to be a TPMT normal metabolizer and NUDT15 intermediate metabolizer. This patient is at risk for myelosuppression with normal doses of 6-Mercaptopurine. Consider starting 6-Mercaptopurine at 30-80\% \of normal dose if normal starting dose is ≥75 mg/m2/day or ≥ 1.5 mg/kg/day  (e.g., start at 25-60 mg/m2/day or 0.45-1.2 mg/kg/day) and adjust doses of Mercaptopurine based on degree of myelosuppression and disease-specific guidelines. Allow 2-4 weeks to reach steady-state after each dose adjustment. If myelosuppression occurs, and depending on other therapy, emphasis should be on reducing Mercaptopurine over other agents. If normal starting dose is already <75mg/m2/day or < 1.5mg/kg/day, dose reduction may not be recommended. Please consult a clinical pharmacist for more information."
        elif pt[s1] == "intermediate_metabolizer" and pt[s2] == "intermediate_metabolizer":
            recommendation = "6-Mercaptopurine can be affected by a patient’s TPMT and NUDT15 phenotype. This patient is predicted to be TPMT intermediate metabolizer and NUDT15 intermediate metabolizer. This patient is at risk for myelosuppression with normal doses of 6-Mercaptopurine. Consider starting 6-Mercaptopurine at 30-80\% \of normal dose if normal starting dose is ≥75 mg/m2/day or ≥ 1.5 mg/kg/day  (e.g., start at 25-60 mg/m2/day or 0.45-1.2 mg/kg/day) and adjust doses of Mercaptopurine based on degree of myelosuppression and disease-specific guidelines.  Allow 2-4 weeks to reach steady-state after each dose adjustment. If myelosuppression occurs, and depending on other therapy, emphasis should be on reducing Mercaptopurine over other agents. If normal starting dose is already <75mg/m2/day or < 1.5mg/kg/day, dose reduction may not be recommended. Please consult a clinical pharmacist for more information."
        elif pt[s1] == "intermediate_metabolizer" and pt[s2] == "poor_metabolizer":
            recommendation = "6-Mercaptopurine can be affected by a patient’s TPMT and NUDT15 phenotype. This patient is predicted to be possible TPMT intermediate metabolizer and NUDT15 intermediate metabolizer. This patient is at risk for myelosuppression with normal doses of 6-Mercaptopurine. Consider starting 6-Mercaptopurine at 30-80\% \of normal dose if normal starting dose is ≥75 mg/m2/day or ≥ 1.5 mg/kg/day  (e.g., start at 25-60 mg/m2/day or 0.45-1.2 mg/kg/day) and adjust doses of Mercaptopurine based on degree of myelosuppression and disease-specific guidelines.  Allow 2-4 weeks to reach steady-state after each dose adjustment. If myelosuppression occurs, and depending on other therapy, emphasis should be on reducing Mercaptopurine over other agents. If normal starting dose is already <75mg/m2/day or < 1.5mg/kg/day, dose reduction may not be recommended. Please consult a clinical pharmacist for more information."
        elif pt[s1] == "poor_metabolizer" and pt[s2] == "normal_metabolizer":
            recommendation = "6-Mercaptopurine can be affected by a patient’s TPMT and NUDT15 phenotype. This patient is predicted to be a TPMT normal metabolizer and NUDT15 poor metabolizer. This patient is at high risk for life threatening myelosuppression with normal doses of 6-Mercaptopurine and should receive greatly reduced doses. For malignancy, initiate dose at 10 mg/m2/day and adjust dose based on myelosuppression and disease-specific guidelines. Allow 4-6 weeks to reach steady state after each dose adjustment.  If myelosuppression occurs, emphasis should be on reducing Mercaptopurine over other agents. Allow 4-6 weeks to reach steady-state after each dose adjustment. If myelosuppression occurs, emphasis should be on reducing Mercaptopurine over other agents. For non-malignant conditions, consider alternative non-thiopurine immunosuppressant therapy. Please consult a clinical pharmacist for more information."
        elif pt[s1] == "poor_metabolizer" and pt[s2] == "intermediate_metabolizer":
            recommendation = "6-Mercaptopurine can be affected by a patient’s TPMT and NUDT15 phenotype. This patient is predicted to be a TPMT poor metabolizer and NUDT15 poor metabolizer. This patient is at high risk for life threatening myelosuppression with normal doses of 6-Mercaptopurine and should receive greatly reduced doses. For malignancy, initiate dose at 10 mg/m2/day and adjust dose based on myelosuppression and disease-specific guidelines. Allow 4-6 weeks to reach steady state after each dose adjustment.  If myelosuppression occurs, emphasis should be on reducing Mercaptopurine over other agents.  For non-malignant conditions, consider alternative non-thiopurine immunosuppressant therapy. Please consult a clinical pharmacist for more information."
        elif pt[s1] == "poor_metabolizer" and pt[s2] == "poor_metabolizer":
            recommendation = "6-Mercaptopurine can be affected by a patient’s TPMT and NUDT15 phenotype. This patient is predicted to be a possible TPMT poor metabolizer and NUDT15 poor metabolizer. This patient is at high risk for life threatening myelosuppression with normal doses of 6-Mercaptopurine and should receive greatly reduced doses. For malignancy, initiate dose at 10 mg/m2/day and adjust dose based on myelosuppression and disease-specific guidelines. Allow 4-6 weeks to reach steady state after each dose adjustment.  If myelosuppression occurs, emphasis should be on reducing Mercaptopurine over other agents. Allow 4-6 weeks to reach steady-state after each dose adjustment. If myelosuppression occurs, emphasis should be on reducing Mercaptopurine over other agents. For non-malignant conditions, consider alternative non-thiopurine immunosuppressant therapy. Please consult a clinical pharmacist for more information."    
        else:
            recommendation = "No recommendation"
    elif s1 in pt and s2 not in pt:
        if pt[s1] == "normal_metabolizer":
            recommendation = "6-Mercaptopurine can be affected by a patient’s TPMT and NUDT15 phenotype. This patient is predicted to be a NUDT15 normal metabolizer; there is no reason to selectively adjust the dose of this medication based on the NUDT15 result. Because a TPMT genotype does not appear to have been ordered for this patient, it is not known if TPMT results would influence the recommended dose or drug. Please consult a clinical pharmacist for more information."
        elif pt[s1] == "intermediate_metabolizer":
            recommendation = "6-Mercaptopurine can be affected by a patient’s TPMT and NUDT15 phenotype. This patient is predicted to be a NUDT15 intermediate metabolizer and is at risk for myelosuppression with normal doses of 6-Mercaptopurine. Consider starting 6-Mercaptopurine at 30-80\% \of normal dose if normal starting dose is ≥75 mg/m2/day or ≥ 1.5 mg/kg/day  (e.g., start at 25-60 mg/m2/day or 0.45-1.2 mg/kg/day) and adjust doses of Mercaptopurine based on degree of myelosuppression and disease-specific guidelines. Allow 2-4 weeks to reach steady-state after each dose adjustment. If myelosuppression occurs, and depending on other therapy, emphasis should be on reducing Mercaptopurine over other agents. If normal starting dose is already <75mg/m2/day or < 1.5mg/kg/day, dose reduction may not be recommended. Because a TPMT genotype does not appear to have been ordered for this patient, it is not known if TPMT results would further influence the recommended dose or drug.  Please consult a clinical pharmacist for more information."
        elif pt[s1] == "poor_metabolizer":
            recommendation = "6-Mercaptopurine can be affected by a patient’s TPMT and NUDT15 phenotype. This patient is predicted to be a NUDT15 poor metabolizer and is at high risk for life threatening myelosuppression with normal doses of 6-Mercaptopurine and should receive greatly reduced doses. Initiate dose at 10 mg/m2/day and adjust dose based on myelosuppression and disease-specific guidelines. Allow 4-6 weeks to reach steady state after each dose adjustment.  If myelosuppression occurs, emphasis should be on reducing Mercaptopurine over other agents. Allow 4-6 weeks to reach steady-state after each dose adjustment. If myelosuppression occurs, emphasis should be on reducing Mercaptopurine over other agents. For non-malignant conditions, consider alternative non-thiopurine immunosuppressant therapy. Because a TPMT genotype does not appear to have been ordered for this patient, it is not known if TPMT results would further influence the recommended dose or drug. Please consult a clinical pharmacist for more information."
        else:
            recommendation = "No recommendation"
    elif s1 not in pt and s2 in pt:
        if pt[s2] == "normal_metabolizer":
            recommendation = "6-Mercaptopurine can be affected by a patient’s TPMT and NUDT15 phenotype. This patient is predicted to be a TPMT normal metabolizer; there is no reason to selectively adjust the dose of this medication based on the TPMT result. Because a NUDT15 genotype does not appear to have been ordered for this patient, it is not known if NUDT15 results would further influence the recommended dose or drug. Please consult a clinical pharmacist for more information."
        elif pt[s2] == "intermediate_metabolizer":
            recommendation = "6-Mercaptopurine can be affected by a patient’s TPMT and NUDT15 phenotype. This patient is predicted to be TPMT intermediate metabolizer and is at risk for myelosuppression with normal doses of 6-Mercaptopurine. Consider starting 6-Mercaptopurine at 30-80\% \of normal dose if normal starting dose is ≥75 mg/m2/day or ≥ 1.5 mg/kg/day  (e.g. start at 25-60 mg/m2/day or 0.45-1.2 mg/kg/day) and adjust doses of Mercaptopurine based on degree of myelosuppression and disease-specific guidelines. Allow 2-4 weeks to reach steady-state after each dose adjustment. If myelosuppression occurs, and depending on other therapy, emphasis should be on reducing Mercaptopurine over other agents. If normal starting dose is already <75mg/m2/day or < 1.5mg/kg/day, dose reduction may not be recommended. Because a NUDT15 genotype does not appear to have been ordered for this patient, it is not known if NUDT15 results would further influence the recommended dose or drug. Please consult a clinical pharmacist for more information."
        elif pt[s2] == "poor_metabolizer":
            recommendation = "6-Mercaptopurine can be affected by a patient’s TPMT and NUDT15 phenotype. This patient is predicted to be a TPMT poor metabolizer and is at high risk for life threatening myelosuppression with normal doses of 6-Mercaptopurine and should receive greatly reduced doses. For malignancy, start with reducing the normal single dose for 6-Mercaptopurine by 90\% \and administer three times a week (e.g., 10 mg/m2/day given just 3 days/week) and adjust doses of Mercaptopurine based on degree of myelosuppression and disease-specific guidelines. Allow 4-6 weeks to reach steady-state after each dose adjustment. If myelosuppression occurs, emphasis should be on reducing Mercaptopurine over other agents. For non-malignant conditions, consider alternative non-thiopurine immunosuppressant therapy. Because a NUDT15 genotype does not appear to have been ordered for this patient, it is not known if NUDT15 results would further influence the recommended dose or drug. Please consult a clinical pharmacist for more information."
        else:
            recommendation = "No recommendation"
    elif s1 not in pt and s2 not in pt: 
        recommendation = "No recommendation"
    return recommendation
