# Step 1 
# Define the output directory path folder
outdir: /Users/kokyriakidis/Desktop/PGxSnake_Output1

# Step 2 
# Define reference build. Select one of hg38 or hg19
build: hg38

# Step 3 
# Set reference file paths.
fasta: /Users/kokyriakidis/Downloads/reference/GRCh38_no_alt_analysis_set.fasta
fai: /Users/kokyriakidis/Downloads/reference/GRCh38_no_alt_analysis_set.fasta.fai

# Step 4 
# Define the datatype of the sequencing data. Select one of ILLUMINA, NANOPORE or PACBIO
datatype: PACBIO

# Step 5 
# Define the path to Stargazer folder
stargazer_path: /Users/kokyriakidis/Downloads/Stargazer_v1.0.8

# Step 6 
# Fill in samples.tsv located inside the config folder
#
# If you have ILLUMINA data fill in the path to the sample's sequenging fasta1 and fasta2 paired end files inside "[]". For example:
# samples: 
#   SAMPLENAME1: [/path/to/sample1/fastq1, /path/to/sample1/fastq2]
#   SAMPLENAME2: [/path/to/sample2/fastq1, /path/to/sample2/fastq2]
#
# If you have NANOPORE or PACBIO data fill in the path to the sample's sequenging fasta file inside "[]". For example:
# samples: 
#   SAMPLENAME1: [/path/to/sample1/fastq]
#   SAMPLENAME2: [/path/to/sample2/fastq]

samples:
  INTEGRATION: [/Users/kokyriakidis/Documents/GitHub/Pharmakon/data/SRR6701493_1.fastq.gz]





css_file: workflow/resources/report/css/styles.css
js_file: workflow/resources/report/js/scripts.js
css_heading: workflow/resources/report/css/heading.css
css_heading: workflow/resources/report/css/body.css


