$schema: "http://json-schema.org/draft-06/schema#"

description: Snakemake configuration file

type: object

properties:
  outdir:
    type: string
    description: Output directory path folder
  build:
    type: string
    enum: ["hg38", "hg19"]
    description: Build of the reference genome [hg38|hg19]
  fasta:
    type: string
    description: Path to reference file
  fai:
    type: string
    description: Path to reference index file
  datatype:
    type: string
    enum: ["ILLUMINA", "PACBIO", "NANOPORE"]
    description: Type of the sequencing data
  stargazer_path:
    type: string
    description: Path to Stargazer folder
  samples:
    type: object
    items: {type: array}
    description: Name of the sample and a list containing it's sequencing reads
required:
  - outdir
  - build
  - fasta
  - fai
  - datatype
  - stargazer_path
  - samples
